name: paulinggrl2022
channels:
  - conda-forge
dependencies:
  # Required for full project functionality (dont remove)
  - pytest
  # Examples (remove and add as needed)
  - jupyterlab
  - xarray
  - numpy
  - scipy
  - dask
  - netcdf4
  - pandas
  - matplotlib
  - cartopy
  - cftime
  - xgcm
  - dask-labextension
  - numba
  - cmocean
  - statsmodels
  - nc-time-axis

